# Filename: app.py

from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

# Create a Flask instance
app = Flask(__name__)

# Configure the SQLAlchemy part of the app instance
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Create the SQLAlchemy db instance
db = SQLAlchemy(app)

# Define a model
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    status = db.Column(db.String(20), nullable=False, default='active')
    datetime = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __repr__(self):
        return f'<User {self.username}>'

# Create the database
with app.app_context():
    db.create_all()

# Define a route to add a user
@app.route('/add_user', methods=['POST'])
def add_user():
    data = request.get_json()
    username = data.get('username')
    email = data.get('email', 'example@example.com')  # Default email if not provided
    status = data.get('status', 'active')  # Default status if not provided

    if not username:
        return jsonify({"error": "Username is required"}), 400

    user = User(username=username, email=email, status=status)
    db.session.add(user)
    db.session.commit()
    return jsonify({"message": f"Added user {username} with email {email}"}), 201

# Define a route to retrieve users
@app.route('/users')
def get_users():
    users = User.query.all()
    return jsonify([
        {
            "username": user.username,
            "email": user.email,
            "status": user.status,
            "datetime": user.datetime
        } for user in users
    ])


# Route for seeing a data
@app.route('/data')
def get_time():
 
    # Returning an api for showing in  reactjs
    return {
        'Name':"geek", 
        "Age":"22",
        "programming": "programming attribute",
        "imgpath": "/media/autogenerated/images.jpeg"
        }

# Run the app
if __name__ == '__main__':
    app.run(debug=True)
