"""Added UserDiary table

Revision ID: 53e524484775
Revises: 6cb46a963183
Create Date: 2024-09-25 17:15:57.005587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e524484775'
down_revision = '6cb46a963183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('film', sa.String(length=255), nullable=False),
    sa.Column('released', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('review_link', sa.String(length=255), nullable=True),
    sa.Column('film_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_diary')
    # ### end Alembic commands ###
